version: '3'
services:

  redis:
    image: redis:alpine
    command: redis-server /data/redis.conf
    volumes:
      - ./redis.conf:/data/redis.conf
      - /opt/redis/data:/data
    networks:
      - bot
    restart: always
    container_name: redis
    ports:
      - '6379:6379'


  arq:
    networks:
      - bot
    container_name: arq
    build:
      context: .
    command: sh -c "python work.py"
    restart: always
    depends_on:
      - redis

  aiogram3:
    networks:
      - bot
    container_name: aiogram3
    build:
      context: .
    command: sh -c "python bot.py"
    restart: always
    depends_on:
      - arq

networks:
  bot:
    driver: bridge
