version: '3'
services:

  redis:
    image: redis:alpine
    networks:
      host: {}
    restart: always
    container_name: redis
    ports:
      - '6379:6379'

  arq:
    networks:
      host: {}
    container_name: arq
    build:
      context: .
    command: sh -c "python work.py"
    restart: always
    depends_on:
      - redis

  aiogram3:
    networks:
      host: {}
    container_name: aiogram3
    build:
      context: .
    command: sh -c "python bot.py"
    restart: always
    depends_on:
      - arq

networks:
  host:
    external: true

