version: '3'
services:

  redis:
    image: redis:alpine
    command: redis-server /data/redis.conf
    volumes:
      - ./redis.conf:/data/redis.conf
      - /opt/redis/data:/data
    networks:
      - bot
    restart: always
    container_name: redis
    ports:
      - '6379:6379'

  app:
    networks:
      - bot
    container_name: app
    build:
      context: .
    volumes:
      - ./auto_db:/app/auto_db
      - ./backup_auto_db:/app/backup_auto_db
    restart: always
    depends_on:
      - redis

networks:
  bot:
    driver: bridge
